export enum ErrorEnum {
    WARINING = "WARNING",
    ERROR = "ERROR",
    BAD_REQUEST = "BAD REQUEST",
    FORBIDDEN = "FORBIDDEN",
    UNAUTHORIZED = "UNAUTHORIZED",
    NOT_FOUND = "NOT FOUND",
    UNKNOWN = "UNKNOWN ERROR"
}